### ISSUE TITLE
Impossible configuration?

### ISSUE THREAD

**Issue by Janno** [plippe/rust-set-game#1]
I am not good at this game but I like playing it every now and then so I was very happy to see your version of it. It works really well. But now it seems to have given me an impossible task. 
![Screenshot_20210708-233045_Trebuchet](https://user-images.githubusercontent.com/70595/124993847-37e43500-e045-11eb-892d-2a33897f30ae.png)
A bug or maybe I am just missing something?

**Comment by plippe** [comment]
Hey,

Thank you for opening a ticket, especially with a screenshot, and sorry for the inconvenience.

The official SET game has some uncertainty.  The Wikipedia article says 1 in 30 deals don't have any matches. Many implementations add a button to deal more cards. This would be consistent with the official rules. 

Yesterday, I committed a "cheat" to guarantee at least one set per deal. 

You shouldn't have any more bum deal.

**Comment by Janno** [comment]
Thank you so much! I appreciate you fixing this so quickly :)
